
import Faq from "react-faq-component";
import "./index.css";
const data = {
    title: "",
    rows: [
        {
            title: "How do I pay my property tax?",
            content: `There are two easy ways:
<br /><br />
Option 1: mSeva Portal

Go to https://mseva.lgpunjab.gov.in/citizen/user/login
Register (if you're a new user) or Login (if you already have an account)
Click on "Search and Pay", or go to "My Properties"
If your property is linked to your registered mobile number, it will show automatically in "My Properties"
Select your property and verify your details
If your property is not yet assessed, complete the assessment first, then proceed to pay
If your property is already assessed, you can pay directly
Complete the payment
<br /><br />
Option 2: WhatsApp Chatbot

Save this number: +91 87509 75975
Send "Hi" on WhatsApp to this number
Choose the option "Pay Property Tax"
Follow the steps to search your property and complete the payment`,
        },
        {
            title: "How to apply & pay Fire NOC?",
            content: `If you mean Punjab mSeva – Fire NOC, the basic process is:
<br /><br />
* Open mSeva Punjab and select Fire NOC / Fire Safety. mSeva supports applying for fire safety certificates online.<br />
* Choose the required service, such as New/Provisional Fire NOC or Renewal.<br />
* Enter applicant/property/building details.
* Upload the required documents. For a new NOC, the Punjab Fire Services FAQ lists:<br />
Ownership proof
Fire drawing/map/plan
Owner checklist/questionnaire
Applicant ID proof
* Submit the application.<br />
* The applicable fee is calculated by the system.<br />
* Click Pay Now and complete payment through the available online payment method.<br />
* Save the application number and payment receipt.<br />
* After approval, the NOC can be downloaded from the Citizen Service Panel; a physical visit is generally not required just to collect the NOC.<br />
<br /><br />
* If payment fails: You normally don't need to create a new application. Log in through Citizen Services → OTP → My Applications, open the existing application, and use the payment option again.`,
        },
        {
            title: "How can I apply for water connection?",
            content: `

New Water Connection – mSeva flow
<br /><br />
1. **Login/Register**<br />

   * Open mSeva Punjab.<br />
   * Login using your mobile number/OTP.<br /><br />

2. Go to **Water & Sewerage**<br /><br />

   * Select **New Water Connection** / **Apply New Water Sewer Connection**. <br /><br />

3. **Select connection details**<br /><br />

   * Water connection<br />
   * Domestic/Commercial, as applicable<br />
   * Enter applicant and property details.<br /><br />

4. **Fill application**<br /><br />

   * Applicant name<br />
   * Father/Husband name<br />
   * Mobile number<br />
   * Address<br />
   * Locality/ULB<br />
   * Property-related details.<br /><br />

5. **Upload required documents**<br /><br />

   * ID/ownership documents as required by the ULB.<br />
   * Submit the application.<br /><br />

6. **Application number**<br /><br />

   * After submission, an **application/reference number** is generated.<br />
   * Use it to track the application.<br />

7. **Payment**<br /><br />

   * After the department calculates/raises the applicable connection charges, the citizen can see the **payment/demand** in the application/dashboard.<br />
   * Click **Pay Now** and complete payment through the available online payment gateway.<br />
   * Download/save the payment receipt.<br />

8. **Connection approval**<br /><br />

   * The department processes the application.<br />
   * After approval and completion of required field work, the water connection is provided.<br />

`,
        },
        {
            title: "What is the difference between Property Unique ID and Old Property ID?",
            content:
                "Old Property Id is an Id previously given by your Local body and can be found on your old payment receipts while Property Unique Id is an Id generated by mSeva system and can be seen post searching your property on this portal. You can search your property using both Ids",
        },
        {
            title: "Why should I apply for a Trade License?",
            content: `A Trade License is permission issued by an Urban Local Body (ULB) to conduct specific trade or business according to the relevant rules, standards and safety guidelines on premises for which it has been issued. Any unauthorised running of trade is an offence which may result in a substantial penalty and subsequent prosecution. Business owners must apply for Trade License before commencement of any trade.`,
        },
        {
            title: "Can I apply for a mutation of my registered property?",
            content: `Yes. You can apply for Mutation online by clicking on ‘Register Property' link under Property Tax section above. Please login, search for your property and open up the details page. You can initiate Mutation process by clicking on 'Transfer Ownership’ option`,
        },
        {
            title: "My property details have changed. How do I make these changes online? Do I need to submit documents while making changes to my existing property details?",
            content: `Currently, you will have to visit your ULB office to make these changes along with documents like ID Proof, Proof of Property Ownership and any other relevant document`,
        },
        {
            title: "How do I check my property tax online?",
            content: `You can check your property tax online by searching for your property`,
        },
        {
            title: "How do I access previous payments made for my property?",
            content: `You can view previous payments made for your property by visiting <a href="https://mseva.lgpunjab.gov.in/citizen/language-selection" target="_blank">this</a> page. Please login, search for your property and open up the details page. You can view previous payments under 'Payment History’ section`,
        },
        {
            title: "How do I renew my trade license?",
            content: `You can renew your Trade License by visiting ‘Renewal of License' option under Trade License section above. Please login, go to ‘My Applications’ under Trade License and click on 'Renew’ for License to be renewed`,
        },
        {
            title: "I have paid my trade license fee. How do I download the payment receipt?",
            content: `You can download payment receipt for your Trade License by visiting <a href="https://mseva.lgpunjab.gov.in/citizen/language-selection" target="_blank">this</a> page. Please login, go to ‘My Applications’ under Trade License and click on License number. You can click on ‘Download’ button to download your receipt`,
        },
        {
            title: "My license application is approved. How do I download the license certificate?",
            content: `You can download license certificate for your Trade License by visiting <a href="https://mseva.lgpunjab.gov.in/citizen/language-selection" target="_blank">this</a> page. Please login, go to ‘My Applications’ under Trade License and click on License number. You can click on ‘Download’ button to download your certificate`,
        },
    ],
};
const styles = {
    bgColor: "#f5f6f7",
    titleTextColor: "#15181d",
    rowTitleColor: "#161b22",
    rowTitleTextSize: "18px",
    rowContentColor: "#4d5966",
    rowContentTextSize: "15px",
    arrowColor: "#f47738",
    rowContentPaddingTop: "16px",
    rowContentPaddingBottom: "20px",
    rowContentPaddingLeft: "24px",
    rowContentPaddingRight: "24px",
    rowTitlePaddingTop: "18px",
    rowTitlePaddingBottom: "18px",
    rowTitlePaddingLeft: "24px",
    rowTitlePaddingRight: "24px",
    borderRadius: "16px",
};

const config = {
    animate: true,
    arrowIcon: "+",
    // tabFocus: true
};
export default function Faqs() {

    return (
        <div id="faqs">
            <Faq
                data={data}
                styles={styles}
                config={config}
            />

        </div>
    )
}